#!/usr/bin/env bash

DIR="$HOME/.config/xmonad"
CONFIG="$DIR/alacritty/alacritty.toml"

if [ "$1" == "--float" ]; then
  ghostty --class='ghostty'
elif [ "$1" == "--full" ]; then
  alacritty --class 'alacritty-fullscreen,alacritty-fullscreen' --config-file "$CONFIG" \
    -o window.startup_mode="'Fullscreen'" \
    window.padding.x=30 window.padding.y=30 \
    window.opacity=0.95 font.size=14
else
  ghostty
fi
