#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## launch alacritty with xmonad config

# xmonad directory
DIR="$HOME/.config/xmonad"
CONFIG="$DIR/alacritty/alacritty.toml"

if [ "$1" == "--float" ]; then
  ghostty --class='alacritty-float,alacritty-float'
elif [ "$1" == "--full" ]; then
  alacritty --class 'alacritty-fullscreen,alacritty-fullscreen' --config-file "$CONFIG" \
    -o window.startup_mode="'Fullscreen'" \
    window.padding.x=30 window.padding.y=30 \
    window.opacity=0.95 font.size=14
else
  ghostty
fi
